#!/usr/bin/env bash
# harness/generate-map.sh
# Auto-generate MAP.md from agent/skill frontmatter and pipeline.json
# Ensures MAP.md is always mechanically accurate, never hand-maintained
# Usage: generate-map.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_DIR="$PROJECT_ROOT/agents"
SKILLS_DIR="$PROJECT_ROOT/skills"
PIPELINE_JSON="$PROJECT_ROOT/harness/pipeline.json"
MAP_FILE="$PROJECT_ROOT/MAP.md"

# Create temporary file for output
TEMP_MAP=$(mktemp)
trap "rm -f $TEMP_MAP" EXIT

# Generate header
cat > "$TEMP_MAP" << 'EOF'
<!-- AUTO-GENERATED by harness/generate-map.sh — do not edit manually -->

# IdeaForge System Map

## Pipeline

```
raw → captured → explored → reviewed → researched → prd_written → arch_written → plan_written → built
```

| State | Description | Artifacts |
|-------|-------------|-----------|
| `raw` | User has shared a raw idea, nothing structured yet | — |
| `captured` | Idea has been clarified and saved as a structured spec | memory/ideas_store.json#latest(stage=structured) |
| `explored` | 10 directions generated, top 3 picked, user chose one | idea_storage/{slug}-{timestamp}/overview.txt, idea_storage/{slug}-{timestamp}/selected.txt |
| `reviewed` | Idea stress-tested across 4 dimensions, verdict issued | memory/ideas_store.json#latest(review.verdict) |
| `researched` | Market research complete — competitors, validation signals, gaps identified | docs/PRODUCT_SENSE.md |
| `prd_written` | PRD written — problem, users, solution, MVP features, constraints defined | docs/product-specs/mvp.md, docs/product-specs/index.md |
| `arch_written` | Architecture designed — components, data flow, tech stack, key decisions | ARCHITECTURE.md |
| `plan_written` | Build plan created — phases, milestones, dependencies, risks | docs/exec-plans/active/mvp-build-plan.md |
| `built` | GitHub repo created, all docs and conductor system pushed | memory/ideas_store.json#latest(github_url), memory/ideas_store.json#latest(stage=built) |

## Agents

| # | Name | Description | Inputs | Outputs | Skills | Depends On | File |
|---|------|-------------|--------|---------|--------|------------|------|
EOF

# Generate agents table
find "$AGENTS_DIR" -name "*.md" -type f | sort | while read -r agent_file; do
  agent_name=$(basename "$agent_file" .md)

  # Extract frontmatter fields
  name=$(sed -n 's/^name: //p' "$agent_file" | head -1)
  stage=$(sed -n 's/^stage: //p' "$agent_file" | head -1)
  description=$(sed -n 's/^description: //p' "$agent_file" | head -1)

  # Extract inputs (multiline YAML array)
  inputs=$(sed -n '/^inputs:/,/^[a-z]/p' "$agent_file" | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')

  # Extract outputs (multiline YAML array)
  outputs=$(sed -n '/^outputs:/,/^[a-z]/p' "$agent_file" | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')

  # Extract skills (multiline YAML array)
  skills=$(sed -n '/^skills:/,/^[a-z]/p' "$agent_file" | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')

  # Extract depends_on (multiline YAML array)
  depends_on=$(sed -n '/^depends_on:/,/^[a-z]/p' "$agent_file" | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')

  # Format for table
  if [ -z "$inputs" ]; then
    inputs="—"
  fi
  if [ -z "$outputs" ]; then
    outputs="—"
  fi
  if [ -z "$skills" ]; then
    skills="—"
  fi
  if [ -z "$depends_on" ]; then
    depends_on="—"
  fi

  # Bold the name
  name_bold="**$name**"

  # Get relative path for agent file
  rel_agent_file="agents/$agent_name.md"

  # Print agent row
  if [ "$stage" = "cross-cutting" ]; then
    echo "| cross-cutting | $name_bold | $description | $inputs | $outputs | $skills | $depends_on | \`$rel_agent_file\` |" >> "$TEMP_MAP"
  else
    echo "| $stage | $name_bold | $description | $inputs | $outputs | $skills | $depends_on | \`$rel_agent_file\` |" >> "$TEMP_MAP"
  fi
done

# Add skills section header
cat >> "$TEMP_MAP" << 'EOF'

## Skills

| Name | Description | Inputs | Outputs | Side Effects | Called By | File |
|------|-------------|--------|---------|-------------|----------|------|
EOF

# Generate skills table
find "$SKILLS_DIR" -name "SKILL.md" -type f | sort | while read -r skill_file; do
  skill_dir=$(dirname "$skill_file")
  skill_name=$(basename "$skill_dir")

  # Extract frontmatter fields
  name=$(sed -n 's/^name: //p' "$skill_file" | head -1)
  description=$(sed -n 's/^description: //p' "$skill_file" | head -1)

  # Extract metadata section (more complex)
  inputs=$(sed -n '/^metadata:/,/^---/p' "$skill_file" | sed -n '/inputs:/,/outputs:/p' | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')
  outputs=$(sed -n '/^metadata:/,/^---/p' "$skill_file" | sed -n '/outputs:/,/side_effects:/p' | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')
  side_effects=$(sed -n '/^metadata:/,/^---/p' "$skill_file" | sed -n '/side_effects:/,/called_by:/p' | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')
  called_by=$(sed -n '/^metadata:/,/^---/p' "$skill_file" | sed -n '/called_by:/,/^---/p' | grep -E '^\s*-' | sed 's/^[[:space:]]*- //' | paste -sd ',' - | sed 's/,/, /g')

  # Format for table
  if [ -z "$inputs" ]; then
    inputs="—"
  fi
  if [ -z "$outputs" ]; then
    outputs="—"
  fi
  if [ -z "$side_effects" ]; then
    side_effects="—"
  fi
  if [ -z "$called_by" ]; then
    called_by="—"
  fi

  # Bold the name
  name_bold="**$name**"

  # Print skill row
  echo "| $name_bold | $description | $inputs | $outputs | $side_effects | $called_by | \`skills/$skill_name/SKILL.md\` |" >> "$TEMP_MAP"
done

# Add transitions section (static for now, could be generated from pipeline.json)
cat >> "$TEMP_MAP" << 'EOF'

## Transitions

| From | To | Agent | Pre-checks | Post-checks |
|------|----|-------|------------|-------------|
| `raw` | `captured` | idea-capturer | — | memory/ideas_store.json contains new idea with stage=structured |
| `captured` | `explored` | idea-explorer | memory/ideas_store.json contains idea with stage=structured | idea_storage/{slug}-{timestamp}/ exists with direction files |
| `explored` | `reviewed` | strategist | memory/ideas_store.json contains idea with direction chosen | memory/ideas_store.json contains review with verdict |
| `reviewed` | `researched` | researcher | review verdict = approved | docs/PRODUCT_SENSE.md populated with market research |
| `researched` | `prd_written` | prd-writer | docs/PRODUCT_SENSE.md exists | docs/product-specs/mvp.md exists |
| `prd_written` | `arch_written` | arch-writer | docs/product-specs/mvp.md exists | ARCHITECTURE.md exists at repository root |
| `arch_written` | `plan_written` | plan-writer | ARCHITECTURE.md exists | docs/exec-plans/active/mvp-build-plan.md exists |
| `plan_written` | `built` | build-orchestrator | review verdict = approved, docs/exec-plans/active/mvp-build-plan.md exists | GitHub repo created, memory/ideas_store.json has stage=built and github_url |
EOF

# Move temp file to final location
mv "$TEMP_MAP" "$MAP_FILE"
echo "✅ MAP.md regenerated with $(find "$AGENTS_DIR" -name "*.md" -type f | wc -l) agents and $(find "$SKILLS_DIR" -name "SKILL.md" -type f | wc -l) skills"
