#!/usr/bin/env python3
"""Generate MAP.md from agent/skill frontmatter and pipeline.json."""

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = ROOT / "agents"
SKILLS_DIR = ROOT / "skills"
PIPELINE_FILE = ROOT / "harness" / "pipeline.json"
OUTPUT_FILE = ROOT / "MAP.md"


def parse_yaml_frontmatter(text: str) -> dict:
    """Extract YAML frontmatter from markdown text (between --- delimiters)."""
    match = re.match(r"^---\n(.*?\n)---", text, re.DOTALL)
    if not match:
        return {}
    return yaml.safe_load(match.group(1)) or {}


def load_agents() -> list[dict]:
    agents = []
    for f in sorted(AGENTS_DIR.glob("*.md")):
        fm = parse_yaml_frontmatter(f.read_text())
        if fm:
            fm["_file"] = f.relative_to(ROOT)
            agents.append(fm)
    return agents


def load_skills() -> list[dict]:
    skills = []
    for f in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        fm = parse_yaml_frontmatter(f.read_text())
        if fm:
            fm["_file"] = f.relative_to(ROOT)
            skills.append(fm)
    return skills


def load_pipeline() -> dict:
    if PIPELINE_FILE.exists():
        return json.loads(PIPELINE_FILE.read_text())
    return {}


def fmt_list(items: list | str) -> str:
    if isinstance(items, list):
        return ", ".join(items) if items else "—"
    return items or "—"


def generate_map() -> str:
    agents = load_agents()
    skills = load_skills()
    pipeline = load_pipeline()

    lines = [
        "<!-- AUTO-GENERATED by harness/generate-map.py — do not edit manually -->",
        "",
        "# IdeaForge System Map",
        "",
    ]

    # Pipeline overview
    if pipeline.get("states"):
        lines.append("## Pipeline")
        lines.append("")
        states = list(pipeline["states"].keys())
        lines.append("```")
        lines.append(" → ".join(states))
        lines.append("```")
        lines.append("")
        lines.append("| State | Description | Artifacts |")
        lines.append("|-------|-------------|-----------|")
        for name, info in pipeline["states"].items():
            artifacts = fmt_list(info.get("artifacts", []))
            lines.append(f"| `{name}` | {info['description']} | {artifacts} |")
        lines.append("")

    # Agents
    lines.append("## Agents")
    lines.append("")
    lines.append("| # | Name | Description | Inputs | Outputs | Skills | Depends On | File |")
    lines.append("|---|------|-------------|--------|---------|--------|------------|------|")
    for a in sorted(agents, key=lambda x: (0 if isinstance(x.get("stage"), int) else 1, x.get("stage", 99))):
        stage = a.get("stage", "—")
        name = a.get("name", "?")
        desc = a.get("description", "")
        inputs = fmt_list(a.get("inputs", []))
        outputs = fmt_list(a.get("outputs", []))
        sk = fmt_list(a.get("skills", []))
        deps = fmt_list(a.get("depends_on", []))
        fpath = a.get("_file", "")
        lines.append(f"| {stage} | **{name}** | {desc} | {inputs} | {outputs} | {sk} | {deps} | `{fpath}` |")
    lines.append("")

    # Skills
    lines.append("## Skills")
    lines.append("")
    lines.append("| Name | Description | Inputs | Outputs | Side Effects | Called By | File |")
    lines.append("|------|-------------|--------|---------|-------------|----------|------|")
    for s in sorted(skills, key=lambda x: x.get("name", "")):
        name = s.get("name", "?")
        desc = s.get("description", "")
        meta = s.get("metadata", {})
        inputs = fmt_list(meta.get("inputs", []))
        outputs = fmt_list(meta.get("outputs", []))
        effects = fmt_list(meta.get("side_effects", []))
        callers = fmt_list(meta.get("called_by", []))
        fpath = s.get("_file", "")
        lines.append(f"| **{name}** | {desc} | {inputs} | {outputs} | {effects} | {callers} | `{fpath}` |")
    lines.append("")

    # Transitions
    if pipeline.get("transitions"):
        lines.append("## Transitions")
        lines.append("")
        lines.append("| From | To | Agent | Pre-checks | Post-checks |")
        lines.append("|------|----|-------|------------|-------------|")
        for t in pipeline["transitions"]:
            pre = fmt_list(t.get("pre_check", []))
            post = fmt_list(t.get("post_check", []))
            lines.append(f"| `{t['from']}` | `{t['to']}` | {t['agent']} | {pre} | {post} |")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    content = generate_map()
    OUTPUT_FILE.write_text(content)
    print(f"Generated {OUTPUT_FILE.relative_to(ROOT)}")
